### ISSUE TITLE
IDF max

### ISSUE THREAD

**Issue by jonvaughan** [simonw/sqlite-fts4#1]
Hi - this isn't actually an issue, more of a question about the bm25 implementation, hope that is OK.  I'm working on a bm25 implementation in kotlin and I figured that if ours came up with the same values as yours, that would mean we had it cracked :)

So the thing is, our results are identical apart from one thing, the difference being caused by the 'max' in this line:

https://github.com/simonw/sqlite-fts4/blob/9f4912f078d47a87aa534b3e835a3422a6d4ad96/sqlite_fts4/__init__.py#L258

And I'm wondering if we should have one too.  The thing is, natural log returns a negative result for values less that 1  - but that could happen if you get a large number of hits relative to the total number of docs I think.  Maybe this is a case that doesn't matter anyway (matching so much that you can't really say they are relevant), maybe i am wrong about the implementation, I'm not sure.  

If you have a few minutes to reply with your thoughts at some point I would really appreciate it.

Thanks

Jon

**Comment by simonw** [comment]
I'll be honest: I can't remember how I decided to write the code like that!

Have you seen my write-up if the project? It might have some useful details for you: https://simonwillison.net/2019/Jan/7/exploring-search-relevance-algorithms-sqlite/

**Comment by jonvaughan** [comment]
:) the article is what put me on to the code (and it was very useful to be able to use the datasette explained query results, nice work there).

Dont worry about this, only idly wondering if you had any thoughts.

**Comment by gustavjon** [comment]
@jonvaughan Did you ever complete that BM25 implementation in Kotlin? And in that case, is is available somewhere as part of some open source project? I'm doing pretty much the same thing so I figured it would save me some time if I could use your implementation as a starting point.
