### ISSUE TITLE
Custom tokenizer interface require

### ISSUE THREAD

**Issue by svjack** [simonw/sqlite-fts4#4]
Hi,
I think add user-defined tokenizer as https://github.com/hideaki-t/sqlite-fts-python
do is a essential function for use fts in sqlite.

**Comment by simonw** [comment]
Yeah that's a really useful feature. I don't think it's relevant to this library though - `sqlite-fts4` exists purely to provide the custom SQL functions I wrote about in https://simonwillison.net/2019/Jan/7/exploring-search-relevance-algorithms-sqlite/
